url=jdbc:databricks://dbc-aa94f872-45bb.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/7e7418076680e931;ConnCatalog=workspace
username=token
password=dapiefd3a8865b0c952ecc3f3815c3e0181d
driver=com.databricks.client.jdbc.Driver
changeLogFile=changelog/db.changelog-master.sql